# docker compose's version
version: '2.19.1'
  # When we ran the container with docker run, the named volume was created automatically.
  # However, that doesn’t happen when running with Compose. 
  # We need to define the volume in the top-level 
  # volumes: section and then specify the mountpoint in the service config.
volumes:
  weblog-mysql-data:


networks:
  weblog-network:


services:
  # region weblog-server ---start
  # name for the service
  # The name will automatically become a network alias
  weblog-server:
    image: weblog-web:0.0.1-SNAPSHOT
    ports:
      - 8888:8080
    volumes:
      - ./weblog-springboot/weblog-web/tomcat-config:/usr/local/tomcat-config
    # can use environment in code
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=weblog
    networks:
      - weblog-network
    # endregion weblog-server  ---end

    # region weblog-mysql ---start
  weblog-mysql:
    image: mysql:8.0
    ports:
      - 3307:3306
    volumes:
      - weblog-mysql-data:/var/lib/mysql
    environment:
      # must provide MYSQL_ROOT_PASSWORD value to mysql
      - MYSQL_ROOT_PASSWORD=root
      # can use params to control it???
      # - MYSQL_DATABASE=weblog
    networks:
      - weblog-network
      # endregion weblog-mysql ---end

      # region weblog-front ---start
  weblog-front:
    image: weblog-vue3:G08CNXDFXSLZIW
    ports:
      - 8889:80
    volumes:
      - ./weblog-vue3/nginx/conf:/etc/nginx/conf.d
    networks:
      - weblog-network
    # endregion weblog-front ---end
