# spring:
#   datasource:
#     # 3307 is port in Docker
#     url: jdbc:mysql://10.167.22.30:3307/weblog?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
#     username: root
#     password: root
#     hikari:
#       minimum-idle: 5
#       maximum-pool-size: 9
#       auto-commit: true
#       idle-timeout: 30000
#       pool-name: Weblog-HikariCP
#       max-lifetime: 1800000
#       connection-timeout: 30000
#       connection-test-query: SELECT 1
  
# #=================================================================
# # log
# #=================================================================
# logging:
#   config: classpath:logback-weblog.xml