spring:
  datasource:
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    # [3307] is port in Docker
#    url: jdbc:mysql://localhost:3307/weblog?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    # [weblog-mysql] is mysql's docker network alias
    # [3306] is mysql's exposed port which it's running on
    url: jdbc:mysql://weblog-mysql:3306/weblog?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 9
      auto-commit: true
      idle-timeout: 30000
      pool-name: Weblog-HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1